// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvDQTG2ZoVBcmJl8KwbrXj4kYuHgn494Q',
    appId: '1:638897917034:web:3ad1ace0c4ae7669fb4e13',
    messagingSenderId: '638897917034',
    projectId: 'finst-5d437',
    authDomain: 'finst-5d437.firebaseapp.com',
    storageBucket: 'finst-5d437.appspot.com',
    measurementId: 'G-P4GCZVHQBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqzBb58jLKVZEGX87trcarsn6ibMMNnck',
    appId: '1:638897917034:android:798dc94240107690fb4e13',
    messagingSenderId: '638897917034',
    projectId: 'finst-5d437',
    storageBucket: 'finst-5d437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfqNMJXIX48zFP52ysmr5Ee4CnziWM24',
    appId: '1:638897917034:ios:116eba5532ae9367fb4e13',
    messagingSenderId: '638897917034',
    projectId: 'finst-5d437',
    storageBucket: 'finst-5d437.appspot.com',
    iosClientId:
        '638897917034-p4fgnjdsm9b8pa2dkrgbpuhi14jikg7i.apps.googleusercontent.com',
    iosBundleId: 'br.com.dreamst.finst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfqNMJXIX48zFP52ysmr5Ee4CnziWM24',
    appId: '1:638897917034:ios:075f7d54eef27dc8fb4e13',
    messagingSenderId: '638897917034',
    projectId: 'finst-5d437',
    storageBucket: 'finst-5d437.appspot.com',
    iosClientId:
        '638897917034-mk775gcan9igs2g47b6k86v288snn8ao.apps.googleusercontent.com',
    iosBundleId: 'br.com.dreamst.finst.RunnerTests',
  );
}
